### PR TITLE
feat: activate github pages

### PR DESCRIPTION
**Pull request by arnoweiss**
needed for publishing the spec docs automatically

### CODE REVIEW

**Comment by netomi** [comment]
I fixed the PR for you, needed to rebase and move the setting to the correct place.

**Comment by netomi** [comment]
as you are just a contributor to the project I suggest to add some fellow committers or project leads as reviewer to approve the request.

**Comment by arnoweiss** [comment]
> I fixed the PR for you, needed to rebase and move the setting to the correct place.

thanks - had the same idea at the same time and force-pushed.
cc @paullatzelsperger can you review this?

**Review by paullatzelsperger — APPROVED** [review]
LGTM

**Review by netomi — APPROVED** [review]

**Pull request merged**
